=== Vano2903/source-testing/integration_tests/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "videoData": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "title": { "type": "string" },
        "thumbMaxResUrl": { "type": "string" },
        "uploadDate": {
          "type": "string",
          "format": "date-time",
          "airbyte_type": "timestamp_without_timezone"
        },
        "Length": { "type": "integer" }
      }
    },
    "wonBy": { "type": "integer" },
    "stats": {
      "type": "object",
      "properties": {
        "synergo": {
          "type": "object",
          "properties": {
            "overall": {
              "type": "object",
              "properties": {
                "tPoints": { "type": "integer" },
                "t25": { "type": "integer" }
              }
            },
            "g1": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            },
            "g2": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            },
            "g3": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            }
          }
        },
        "redez": {
          "type": "object",
          "properties": {
            "overall": {
              "type": "object",
              "properties": {
                "tPoints": { "type": "integer" },
                "t25": { "type": "integer" }
              }
            },
            "g1": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            },
            "g2": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            },
            "g3": {
              "type": "object",
              "properties": {
                "points": { "type": "integer" },
                "n25": { "type": "integer" },
                "valFe": { "type": "integer" },
                "character": { "type": "string" }
              }
            }
          }
        }
      }
    },
    "comment": { "type": "string" },
    "addedBy": { "type": "string" }
  }
}

=== Vano2903/source-testing/integration_tests/example.json
{
  "videoData": {
    "id": "mkelvKLWIZg",
    "title": "COME HA FATTO? - PEGGLE",
    "thumbMaxResUrl": "https://i.ytimg.com/vi/mkelvKLWIZg/maxresdefault.jpg",
    "uploadDate": "2022-03-15T17:00:21Z",
    "Length": 589
  },
  "wonBy": 0,
  "stats": {
    "synergo": {
      "overall": {
        "tPoints": 171650,
        "t25": 1
      },
      "g1": {
        "points": 68930,
        "n25": 0,
        "valFe": 0,
        "character": "unicorno"
      },
      "g2": {
        "points": 41440,
        "n25": 1,
        "valFe": 0,
        "character": "unicorno"
      },
      "g3": {
        "points": 61280,
        "n25": 0,
        "valFe": 25000,
        "character": "unicorno"
      }
    },
    "redez": {
      "overall": {
        "tPoints": 237124,
        "t25": 0
      },
      "g1": {
        "points": 113324,
        "n25": 0,
        "valFe": 5000,
        "character": "coniglio"
      },
      "g2": {
        "points": 54940,
        "n25": 0,
        "valFe": 5000,
        "character": "coniglio"
      },
      "g3": {
        "points": 68860,
        "n25": 0,
        "valFe": 0,
        "character": "coniglio"
      }
    }
  },
  "comment": "ciao",
  "addedBy": "vano"
}
